name: 🐛 Bug Report
description: Report a bug or unexpected behavior with PSWimToolkit.
labels: [bug, needs-review]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Thank you for reporting a bug!

        Please provide as much information as possible to help us fix the issue.
        **Write N/A in sections that do not apply.**

  - type: textarea
    id: description
    attributes:
      label: Bug description
      description: A clear and concise description of the bug.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproducible
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Run command '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expectedBehavior
    attributes:
      label: Expected behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: currentBehavior
    attributes:
      label: Actual behavior
      description: What actually happened.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error messages / Verbose logs
      description: |
        Any error messages or verbose output. **Obfuscate sensitive information.**
      placeholder: Paste logs here...
      render: text
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem (especially for GUI issues).
    validations:
      required: false

  - type: input
    id: moduleVersion
    attributes:
      label: PSWimToolkit version
      description: Run `Get-Module PSWimToolkit -ListAvailable | Select-Object Version`
      placeholder: "1.0.0"
    validations:
      required: true

  - type: textarea
    id: psVersion
    attributes:
      label: PowerShell version
      description: Run `$PSVersionTable`
      render: text
    validations:
      required: true

  - type: textarea
    id: osInfo
    attributes:
      label: Operating system
      description: |
        Run: `Get-ComputerInfo -Property @('OsName','OSArchitecture','WindowsVersion','WindowsBuildLabEx')`
      placeholder: Windows 11 Pro, 23H2, x64...
      render: text
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected area
      description: Which part of the module is affected?
      options:
        - GUI / User Interface
        - WIM Image Mounting
        - Update Integration (MS Catalog)
        - Provisioning / Automation
        - Installation / Import
        - Other
    validations:
      required: true

  - type: textarea
    id: suggestedSolution
    attributes:
      label: Possible solution
      description: If you have any ideas on how to fix this, please share.
    validations:
      required: false
